# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ImageAppUnsplash' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ImageAppUnsplash

pod 'Alamofire'
pod 'DTPagerController'
pod 'RxSwift'
pod 'RxCocoa' 
pod 'TinderSwipeView'  

  target 'ImageAppUnsplashTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ImageAppUnsplashUITests' do
    # Pods for testing
  end

end
