# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ImageAppUnsplash' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!

  # Pods for ImageAppUnsplash
  pod "Koloda"
  pod 'Alamofire', '~> 5.2'
  pod 'AlamofireImage', '~> 4.1'
  pod 'Firebase/Firestore'
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
end

  target 'ImageAppUnsplashTests' do
    pod 'Firebase/Firestore'
  end

